---
title: Mini Stream player
email: hello@jogjapp.com
description: |
  Stream Player homepage
baseurl: ''
url: ''
twitter_username: jogjapp
github_username: jogjapp
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
